[package]
name = "nchat-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.4.3"
dioxus-desktop = "0.4.3"
sha2 = "0.10.8"
sqlx = "0.7.4"
tokio-tungstenite = "0.21.0"
